### ISSUE TITLE
Analyser string parsing

### ISSUE THREAD

**Issue by andylhxu** [yogeshg/clayer#6]
# Issues
1. Does not support parsing longer than 10240 characters in a log line.
2. Does not support parsing new lines created by users.
# Improvements
`std::regex` support in `v1.2`.

**Comment by yogeshg** [comment]
see https://github.com/yogeshg/clayer/pull/7

* `std::readline` supports reading into `std::string`
* started using `regex`s but we still do not support user generated new lines

user generated new lines to be supported in `v1.2`
